import type { Locale } from './index';

type Translation = { description: string; body?: string[] };

const translations: Record<string, Record<'en' | 'bs', Translation>> = {
  'alo-038': {
    en: { description: 'A comedy performed at the Academy of Arts in Pristina that marked Ilir Tafa’s stage debut.' },
    bs: { description: 'Komedija izvedena na Akademiji umjetnosti u Prištini, kojom je Ilir Tafa debitovao na sceni.' },
  },
  'atje-ku-nuk-lind-dielli': {
    en: { description: 'A Kosovo drama about life and resilience during the difficult pre-war period, and one of Tafa’s earliest film projects.' },
    bs: { description: 'Kosovska drama o životu i istrajnosti u teškom predratnom periodu, te jedan od Tafinih prvih filmskih projekata.' },
  },
  bretkosa: {
    en: { description: 'A stage drama directed by Burbuqe Berisha that explores the psychological wounds left by the war in Kosovo through four people searching for meaning and healing.', body: ['“Bretkosa” is a theatre production directed by Burbuqe Berisha and based on a text by Croatian playwright Dubravko Mihanović. Staged by AAB’s Faruk Begolli Theatre, it explores the psychological wounds and consequences of the war in Kosovo through four characters confronting loneliness, trauma, addiction, and the search for meaning after a painful past.', 'Combining realistic drama with powerful emotion, “Bretkosa” portrays the human struggle for healing and change in a society fractured by memories of war. Featuring a powerful performance by Ilir Tafa as the barber, alongside Basri Shala, Valmir Krasniqi, and Lum Veseli, the production has been praised for its sensitivity and focus on ordinary people trying to rebuild their lives.'] },
    bs: { description: 'Pozorišna drama u režiji Burbuqe Berishe koja kroz četiri osobe u potrazi za smislom i iscjeljenjem istražuje psihološke rane rata na Kosovu.', body: ['„Bretkosa“ je pozorišna predstava rediteljice Burbuqe Berishe, zasnovana na tekstu hrvatskog dramatičara Dubravka Mihanovića. U produkciji teatra „Faruk Begolli“ pri AAB-u, predstava govori o psihološkim ranama i posljedicama rata na Kosovu kroz sudbine četiri lika suočena sa samoćom, traumom, ovisnošću i potragom za smislom nakon bolne prošlosti.', 'Spajajući realističku dramu i snažne emocije, „Bretkosa“ prikazuje ljudsku borbu za iscjeljenje i promjenu u društvu obilježenom sjećanjem na rat. Uz snažnu interpretaciju Ilira Tafe u ulozi brijača te Basrija Shale, Valmira Krasniqija i Luma Veselija, predstava je pohvaljena zbog svoje osjećajnosti i usmjerenosti na običnog čovjeka koji pokušava obnoviti život.'] },
  },
  invisible: {
    en: { description: 'A fantasy drama about trauma and isolation, told through a boy who believes he has become invisible after a serious accident.', body: ['“Invisible (Nevidljivi)” is a fantasy-drama series about trauma and the human inner world. It follows Capi, a twelve-year-old boy who begins to believe that he is invisible after a serious accident. His sessions with a psychologist reveal that this “invisibility” is a metaphor for the pain and isolation he experiences.', 'The film combines psychological drama with fantastical symbolism, reflecting on how children and adults confront trauma and feelings of abandonment.'] },
    bs: { description: 'Fantastična drama o traumi i izolaciji, ispričana kroz priču o dječaku koji nakon teške nesreće vjeruje da je postao nevidljiv.', body: ['„Invisible (Nevidljivi)“ je fantastična dramska serija o traumi i čovjekovom unutrašnjem svijetu. Priča prati Capija, dvanaestogodišnjeg dječaka koji nakon teške nesreće počinje vjerovati da je nevidljiv. Kroz razgovore s psihologinjom otkriva se da je njegova „nevidljivost“ metafora za bol i izolaciju koje proživljava.', 'Film spaja psihološku dramu i fantastični simbolizam te razmatra način na koji se djeca i odrasli suočavaju s traumom i osjećajem napuštenosti.'] },
  },
  kacurrelet: {
    en: { description: 'A popular RTK comedy series portraying the everyday life of a Kosovo family.' },
    bs: { description: 'Popularna humoristička serija RTK-a koja prikazuje svakodnevni život jedne kosovske porodice.' },
  },
  'kamera-me-yjet': {
    en: { description: 'An early Kosovo television series combining social themes with situational comedy.' },
    bs: { description: 'Rana kosovska televizijska serija koja spaja društvene teme i komediju situacije.' },
  },
  'kandidati-per-president': {
    en: { description: 'A political satire in which Ilir Tafa plays the President, humorously reflecting the political reality of the post-war years.' },
    bs: { description: 'Politička satira u kojoj Ilir Tafa igra predsjednika i humorom oslikava političku stvarnost poslijeratnih godina.' },
  },
  'killing-me-softly': {
    en: { description: 'A theatre comedy about modern relationships and the absurdity of human communication, explored through comic situations and misunderstandings.', body: ['“Killing Me Softly” is a theatre comedy staged at Dodona Theatre in Pristina and directed by Admir Glamočak. It places modern relationships and the absurdity of human communication at the centre of the story.', 'The action revolves around Bruno, played by Ilir Tafa, a man caught in a web of comic situations and misunderstandings that expose the contrast between love, self-interest, and loneliness in contemporary life. Through fast-paced dialogue and intelligent humour, the production satirises romantic relationships and personal egos while revealing both the irony and humanity of its characters.'] },
    bs: { description: 'Pozorišna komedija o savremenim odnosima i apsurdu ljudske komunikacije, prikazanim kroz komične situacije i nesporazume.', body: ['„Killing Me Softly“ je pozorišna komedija postavljena u teatru Dodona u Prištini, u režiji Admira Glamočaka. U središtu predstave su savremeni odnosi i apsurd ljudske komunikacije.', 'Radnja se odvija oko Brune, kojeg igra Ilir Tafa, čovjeka upletenog u mrežu komičnih situacija i nesporazuma koji otkrivaju suprotnost između ljubavi, interesa i samoće u savremenom životu. Brzim dijalozima i inteligentnim humorom predstava ismijava ljubavne odnose i lični ego, istovremeno otkrivajući ironiju i ljudskost svojih likova.'] },
  },
  'kodi-i-jetes': {
    en: { description: 'A drama by Ekrem Kryeziu about the human and moral wounds of the Kosovo war, following people searching for meaning amid destruction.', body: ['“Kodi i Jetës” is a 2012 drama written and directed by Ekrem Kryeziu that addresses the human and moral wounds caused by the Kosovo war.', 'Set during 1998–1999, it follows several people confronting loss, fear, exile, and the search for meaning amid destruction. Through intertwined stories, the film explores war as both a physical and spiritual experience, showing how hope remains the final code that keeps people alive.', 'The cast includes Ilir Tafa, Bubulina Lajçi, Çun Lajçi, Xhevat Qorraj, and Mentor Zumberaj, whose authentic performances bring emotional realism and deep sensitivity to the film.', '“Kodi i Jetës” is a poetic reflection on resilience, pain, and faith in humanity—a cinematic testimony to the wounds of war and the strength of the Kosovo spirit.'] },
    bs: { description: 'Drama Ekrema Kryeziua o ljudskim i moralnim ranama rata na Kosovu, kroz priče ljudi koji usred razaranja tragaju za smislom.', body: ['„Kodi i Jetës“ je drama iz 2012. godine, prema scenariju i u režiji Ekrema Kryeziua, koja govori o ljudskim i moralnim ranama nastalim tokom rata na Kosovu.', 'Radnja je smještena u 1998. i 1999. godinu i prati nekoliko ljudi suočenih s gubitkom, strahom, izgnanstvom i potragom za smislom usred razaranja. Kroz isprepletene priče film istražuje rat kao fizičko i duhovno iskustvo te pokazuje kako nada ostaje posljednji kod koji ljude održava u životu.', 'U filmu igraju Ilir Tafa, Bubulina Lajçi, Çun Lajçi, Xhevat Qorraj i Mentor Zumberaj, čije autentične izvedbe donose emocionalni realizam i duboku osjećajnost.', '„Kodi i Jetës“ je poetsko promišljanje o otpornosti, boli i vjeri u čovječnost—filmsko svjedočanstvo o ratnim ranama i snazi kosovskog duha.'] },
  },
  'konak-kod-hilmije': {
    en: { description: 'A Bosnian historical comedy series that uses humour and satire to depict life in occupied Sarajevo during the Second World War.', body: ['“Konak kod Hilmije” is a Bosnian historical comedy series created by Feđa Isović and directed by Elmir Jukić. Through humour and satire, it portrays life in occupied Sarajevo during the Second World War.', 'The story unfolds in Hilmija’s inn, where Germans, Partisans, Ustaše, and civilians meet while trying to survive the intrigue and absurdity of war.', 'Ilir Tafa plays Agim Rugoba, an Albanian character who brings distinctive authenticity and energy to the story. With its original screenplay and excellent performances, “Konak kod Hilmije” became one of the region’s most successful series.'] },
    bs: { description: 'Bosanskohercegovačka historijska humoristička serija koja humorom i satirom prikazuje život u okupiranom Sarajevu tokom Drugog svjetskog rata.', body: ['„Konak kod Hilmije“ je bosanskohercegovačka historijska humoristička serija autora Feđe Isovića, u režiji Elmira Jukića, koja humorom i satirom prikazuje život u okupiranom Sarajevu tokom Drugog svjetskog rata.', 'Radnja se odvija u Hilmijinom konaku, gdje se susreću Nijemci, partizani, ustaše i civili koji pokušavaju preživjeti spletke i apsurd rata.', 'Ilir Tafa igra Agima Rugobu, albanski lik koji priči donosi posebnu autentičnost i energiju. Zahvaljujući originalnom scenariju i izvrsnim glumačkim izvedbama, „Konak kod Hilmije“ postao je jedna od najuspješnijih serija u regionu.'] },
  },
  'lud-zbunjen-normalan': {
    en: { description: 'One of the Balkans’ best-known comedy series, portraying the everyday life of three generations of Sarajevo’s Fazlinović family through humour and irony.', body: ['“Lud, Zbunjen, Normalan” is one of the best-known comedy series in the Balkans. Created by Feđa Isović and directed by Elmir Jukić, it aired from 2007 to 2021, spanning more than 300 episodes across 13 seasons.', 'The story takes place in Sarajevo, in the Fazlinović family apartment, where three generations live together: grandfather Izet, his son Faruk, and grandson Damir. Through comic situations and irony-filled dialogue, the series explores everyday life, generational conflict, and the absurdities of post-Yugoslav reality.', 'Ilir Tafa appears in one of the series’ most notable storylines as Mentor Kosova, co-owner of Faruk’s studio and a character who brings a distinctly Albanian energy and humour to the screen. Tafa’s charismatic presence enriches the show’s cultural mosaic and strengthens the connection among the region’s cultures.', '“Lud, Zbunjen, Normalan” remains one of Balkan television’s most beloved series because of its authenticity, intelligent humour, and characters who accurately reflect the region’s shared society.'] },
    bs: { description: 'Jedna od najpoznatijih balkanskih humorističkih serija, koja humorom i ironijom prati svakodnevni život tri generacije sarajevske porodice Fazlinović.', body: ['„Lud, zbunjen, normalan“ jedna je od najpoznatijih humorističkih serija na Balkanu. Autor serije je Feđa Isović, reditelj Elmir Jukić, a emitovana je od 2007. do 2021. godine u više od 300 epizoda i 13 sezona.', 'Radnja se odvija u Sarajevu, u stanu porodice Fazlinović, gdje zajedno žive tri generacije: djed Izet, sin Faruk i unuk Damir. Kroz komične situacije i ironične dijaloge serija govori o svakodnevnom životu, generacijskim sukobima i apsurdu postjugoslavenske stvarnosti.', 'Ilir Tafa pojavljuje se u jednoj od zapaženijih priča kao Mentor Kosova, suvlasnik Farukovog studija i lik koji na ekran donosi prepoznatljivu albansku energiju i humor. Tafinom harizmatičnom pojavom obogaćen je kulturni mozaik serije i ojačana veza među kulturama regiona.', '„Lud, zbunjen, normalan“ ostaje jedna od najomiljenijih serija balkanske televizije zahvaljujući autentičnosti, inteligentnom humoru i likovima koji precizno oslikavaju zajedničko društvo regiona.'] },
  },
  'shtepia-e-tmerrit': {
    en: { description: 'A cult Kosovo horror comedy that brought humour and suspense to the screen in the post-war period.' },
    bs: { description: 'Kultna kosovska horor-komedija koja je u poslijeratnom periodu spojila humor i napetost.' },
  },
  'shtepia-ime': {
    en: { description: 'A Kosovo television series following the relationships, challenges, and everyday life of a family.', body: ['“Shtëpia ime” is a Kosovo drama series produced by Arenafilm in 2011–2012 and broadcast on RTK.', 'Written and directed by Sunaj Raça, the project presents a powerful social drama about economic hardship, personal challenges, and the realities of life in post-war Kosovo.', 'The series brings together several prominent Albanian actors, including Enver Petrovci, Ilir Tafa, Selman Jusufi, and Sunaj Raça.'] },
    bs: { description: 'Kosovska televizijska serija koja prati odnose, izazove i svakodnevni život jedne porodice.', body: ['„Shtëpia ime“ je kosovska dramska serija koju je Arenafilm producirao 2011. i 2012. godine, a emitovana je na RTK-u.', 'Prema scenariju i u režiji Sunaja Raçe, ovaj projekt donosi snažnu socijalnu dramu o izazovima, ekonomskim teškoćama i stvarnosti života na poslijeratnom Kosovu.', 'Serija okuplja nekoliko poznatih albanskih glumaca, među kojima su Enver Petrovci, Ilir Tafa, Selman Jusufi i Sunaj Raça.'] },
  },
  'sonte-jam-vetem': {
    en: { description: 'An intimate stage drama about loneliness, memory, and the need for love, told through two people confronting separation and a failure to communicate.', body: ['“Sonte jam vetëm” is an intimate theatre drama written by Andrea Pol Antoan and directed by Enver Petrovci. It tells an emotional story about loneliness, memory, and the need for love in a world that often forgets the individual.', 'At its centre are two characters played by Ilir Tafa and Niada Saliasi. Through emotionally charged dialogue, they reveal the separation, disappointment, and longing each carries. With its measured pace, poetic contrasts of light and shadow, and inner tension, Petrovci’s production combines psychological theatre with a cinematic aesthetic.', 'Disillusioned with married life, she goes so far as to report her husband, while he, divided between his inner and outer worlds, tries to find meaning in silence. Through this contrast, Petrovci creates a reflection on loneliness as a universal condition and on our inability to communicate our deepest feelings.', 'Acclaimed as one of the most-watched productions of 2010 and presented at the International Theatre Festival in Sarajevo, “Sonte jam vetëm” remains a powerful meditation on human loneliness and the search for a spiritual connection beyond words.'] },
    bs: { description: 'Intimna pozorišna drama o samoći, sjećanju i potrebi za ljubavlju, kroz dvoje ljudi suočenih s rastankom i nemogućnošću komunikacije.', body: ['„Sonte jam vetëm“ je osjećajna pozorišna drama autora Andree Pola Antoana, u režiji Envera Petrovcija. Predstava donosi emotivnu priču o samoći, sjećanjima i potrebi za ljubavlju u svijetu koji često zaboravlja pojedinca.', 'U središtu su dva lika koja igraju Ilir Tafa i Niada Saliasi. Kroz dijaloge ispunjene osjećajima otkrivaju rastanke, razočaranja i čežnju koju svako od njih nosi. Sporim ritmom, poetskim odnosom svjetla i sjene te unutrašnjom napetošću, Petrovcijeva predstava spaja psihološko pozorište i filmsku estetiku.', 'Razočarana bračnim životom, ona odlazi toliko daleko da prijavljuje supruga, dok on, podijeljen između unutrašnjeg i vanjskog svijeta, pokušava pronaći smisao u tišini. Tim kontrastom Petrovci gradi promišljanje o samoći kao univerzalnom stanju i čovjekovoj nesposobnosti da izrazi najdublja osjećanja.', 'Hvaljena kao jedna od najgledanijih predstava 2010. i izvedena na Međunarodnom pozorišnom festivalu u Sarajevu, „Sonte jam vetëm“ ostaje snažno promišljanje o ljudskoj samoći i potrazi za duhovnom povezanošću izvan riječi.'] },
  },
  'studio-2': {
    en: { description: 'A comedy staged at Dodona Theatre that portrays urban life in Pristina during the 1990s.' },
    bs: { description: 'Komedija izvedena u teatru Dodona koja prikazuje urbani život Prištine tokom devedesetih godina.' },
  },
  'svetica-tame': {
    en: { description: 'A stage drama exploring Mother Teresa’s spiritual life and inner dilemmas through reflections on faith, sacrifice, and humanity.', body: ['“Svetica Tame” is a theatre drama written by Venko Andonovski and directed by Gradimir Gojer that explores Mother Teresa’s inner life and spiritual dilemmas.', 'The story begins as she receives the Nobel Peace Prize. Through profound dialogue, it reveals the saint’s human side: the conflicts between faith and doubt, love and pain, mission and spiritual exhaustion.', 'The production unites actors from Bosnia and Herzegovina, Croatia, and Kosovo in a regional project of deep human sensitivity. Ilir Tafa also appears in the production, contributing to its meditative and dramatic atmosphere.', '“Svetica Tame” is a theatrical reflection on sacrifice, faith, and the human struggle to preserve light in the darkness of the soul.'] },
    bs: { description: 'Pozorišna drama koja istražuje duhovni život i unutrašnje dileme Majke Tereze kroz razmišljanja o vjeri, žrtvi i humanosti.', body: ['„Svetica Tame“ je pozorišna drama Venka Andonovskog, u režiji Gradimira Gojera, koja istražuje unutrašnji život i duhovne dileme Majke Tereze.', 'Radnja počinje u trenutku kada prima Nobelovu nagradu za mir. Kroz duboke dijaloge otkriva se ljudska strana svetice: sukobi između vjere i sumnje, ljubavi i boli, misije i duhovne iscrpljenosti.', 'Predstava okuplja glumce iz Bosne i Hercegovine, Hrvatske i Kosova, stvarajući regionalni projekt duboke ljudske osjećajnosti. U produkciji učestvuje i Ilir Tafa, čija izvedba doprinosi meditativnoj i dramskoj atmosferi djela.', '„Svetica Tame“ je pozorišno promišljanje o žrtvi, vjeri i čovjekovoj borbi da sačuva svjetlost u tami duše.'] },
  },
  terorista: {
    en: { description: 'A drama about radicalisation and ideological manipulation, following a man who loses control amid fear and violence.', body: ['“Terorista” is a 2016 drama filmed in Sarajevo and Budapest, starring Ilir Tafa in the leading role. It examines radicalisation, ideological manipulation, and the consequences that arise when an individual becomes involved in extremist networks under the guise of idealism.', 'The story follows a man who, disillusioned with social and political reality, becomes involved in a secret organisation without fully realising that he is entering a system that uses fear and violence to achieve its goals. His journey becomes a metaphor for the loss of control, conscience, and humanity in a divided world.'] },
    bs: { description: 'Drama o radikalizaciji i ideološkoj manipulaciji, kroz priču o čovjeku koji gubi kontrolu između straha i nasilja.', body: ['„Terorista“ je drama iz 2016. godine, snimana u Sarajevu i Budimpešti, s Ilirom Tafom u glavnoj ulozi. Film se bavi radikalizacijom, ideološkom manipulacijom i posljedicama koje nastaju kada se pojedinac, pod maskom idealizma, uključi u ekstremističke mreže.', 'Priča prati čovjeka koji se, razočaran društvenom i političkom stvarnošću, priključuje tajnoj organizaciji ne shvatajući u potpunosti da postaje dio sistema koji koristi strah i nasilje za ostvarenje svojih ciljeva. Njegovo putovanje postaje metafora gubitka kontrole, savjesti i ljudskosti u podijeljenom svijetu.'] },
  },
  'the-life-of-flowers': {
    en: { description: 'A Bosnian-American feature film about life, identity, and hope, following a young man facing migration and the fear of deportation.', body: ['“The Life of Flowers” is a Bosnian-American feature-film co-production that had its world premiere at the Sarajevo Film Festival. It follows a young man from Sarajevo facing everyday hardship, the struggle to build a better future, and the fear of deportation from the country where he lives.', 'Through an intimate, atmospheric narrative, the film explores identity, migration, and hope, showing that even in the harshest realities there is a small beauty to life—like flowers growing in the midst of a battlefield.', 'In this international co-production, Ilir Tafa gives a sensitive and authentic performance, enriching the film with his natural presence and experience on Balkan screens.'] },
    bs: { description: 'Bosansko-američki igrani film o životu, identitetu i nadi, kroz priču o mladiću suočenom s migracijom i strahom od deportacije.', body: ['„The Life of Flowers“ je bosansko-američki koprodukcijski igrani film koji je svjetsku premijeru imao na Sarajevo Film Festivalu. Prati mladića iz Sarajeva suočenog sa svakodnevnim teškoćama, nastojanjem da izgradi bolju budućnost i strahom od deportacije iz zemlje u kojoj živi.', 'Intimnom i atmosferičnom pričom film istražuje identitet, migraciju i nadu, pokazujući da čak i u najsurovijoj stvarnosti postoji mala ljepota života—poput cvijeća koje raste usred bojnog polja.', 'U ovoj međunarodnoj koprodukciji Ilir Tafa donosi osjećajnu i autentičnu interpretaciju, obogaćujući film prirodnom prisutnošću i iskustvom s balkanskih ekrana.'] },
  },
  'tre-vllaznit': {
    en: { description: 'A Kosovo television comedy broadcast on ATV. Launched in 2022, it quickly became one of the country’s most-watched local productions.', body: ['“Tre Vllaznit” is a Kosovo television comedy produced in Kosovo and broadcast on ATV. The series premiered in 2022 and quickly became one of the country’s most-watched local productions.', 'Set in Pristina in the Bytyqi family home, it follows three generations living under the same roof. The series explores their complicated relationships, everyday comic conflicts, and generational differences—from Bajram, the family patriarch, to his sons and grandchildren, who each confront modern life in their own way.', 'The renowned actor Ilir Tafa plays Bajram Bytyqi, bringing humour, wisdom, and energy to a character who realistically reflects the everyday life of many Albanian families.'] },
    bs: { description: 'Kosovska televizijska komedija emitovana na ATV-u. Nakon premijere 2022. brzo je postala jedna od najgledanijih domaćih produkcija.', body: ['„Tre Vllaznit“ je kosovska televizijska komedija proizvedena na Kosovu i emitovana na ATV-u. Serija je počela 2022. godine i brzo postala jedna od najgledanijih domaćih produkcija.', 'Radnja se odvija u Prištini, u domu porodice Bytyqi, gdje tri generacije žive pod istim krovom. Serija prikazuje njihove složene odnose, svakodnevne komične sukobe i generacijske razlike—od Bajrama, patrijarha porodice, do njegovih sinova i unuka, koji se na različite načine suočavaju sa savremenim životom.', 'Poznati glumac Ilir Tafa igra Bajrama Bytyqija i donosi lik ispunjen humorom, mudrošću i energijom, realistično oslikavajući svakodnevni život brojnih albanskih porodica.'] },
  },
  'zaba-2017': {
    en: { description: 'A drama about trauma and life in post-war Sarajevo, following a barber confronting painful memories and guilt from the past.', body: ['“Žaba” (The Frog) is a 2017 drama directed by Elmir Jukić and written by Pjer Žalica, based on the stage play of the same name. A co-production between Bosnia and Herzegovina, Croatia, and Macedonia, the film received recognition at numerous regional festivals.', 'The story follows Zeko, a barber in post-war Sarajevo who suffers from post-traumatic stress disorder. He attempts to make a new start by gathering his old friends for a celebration, but their evening turns into a confrontation with the past, guilt, and the hope of forgiveness.', 'Using simple yet emotional dialogue, the film reveals the emptiness and irony of life after conflict. Ilir Tafa’s restrained performance contributes to its powerful dramatic atmosphere and reinforces the realism and authenticity that make “Žaba” one of contemporary Balkan cinema’s most moving works.'] },
    bs: { description: 'Drama o traumi i životu u poslijeratnom Sarajevu, kroz priču o brijaču suočenom s bolnim sjećanjima i krivicom iz prošlosti.', body: ['„Žaba“ je drama iz 2017. godine, u režiji Elmira Jukića i prema scenariju Pjera Žalice, zasnovana na istoimenoj pozorišnoj predstavi. Film je koprodukcija Bosne i Hercegovine, Hrvatske i Makedonije i nagrađivan je na brojnim regionalnim festivalima.', 'Priča prati Zeku, brijača u poslijeratnom Sarajevu koji pati od posttraumatskog stresnog poremećaja. Pokušava početi iznova okupljajući stare prijatelje na proslavi, ali se njihova noć pretvara u suočavanje s prošlošću, krivicom i nadom u oprost.', 'Jednostavnim, ali emotivnim dijalozima film prikazuje prazninu i ironiju života nakon sukoba. Suzdržana igra Ilira Tafe doprinosi snažnoj dramskoj atmosferi te pojačava realizam i autentičnost zbog kojih je „Žaba“ jedno od najdirljivijih djela savremene balkanske kinematografije.'] },
  },
  'zogjte-e-luftes': {
    en: { description: 'A Kosovo television tragedy starring Ilir Tafa as Agimi, exploring the psychological and social consequences of war.', body: ['“Zogjtë e Luftës” (War Birds) is a Kosovo television drama starring Ilir Tafa in the leading role of Agimi. A tragedy, the series explores the psychological and social consequences of war.', '“Zogjtë e Luftës” consists of 20 episodes presenting events and characters that reflect everyday life during and after the war.'] },
    bs: { description: 'Kosovska televizijska tragedija u kojoj Ilir Tafa igra Agimija, a koja istražuje psihološke i društvene posljedice rata.', body: ['„Zogjtë e Luftës“ (Ratne ptice) kosovska je televizijska drama u kojoj Ilir Tafa igra glavnu ulogu Agimija. Serija pripada žanru tragedije i govori o psihološkim i društvenim posljedicama rata.', '„Zogjtë e Luftës“ sastoji se od 20 epizoda koje prikazuju događaje i likove što odražavaju svakodnevni život tokom i nakon rata.'] },
  },
};

export function getWorkTranslation(slug: string, locale: Locale): Translation | undefined {
  if (locale === 'sq') return undefined;
  return translations[slug]?.[locale];
}
